engines:
  checkstyle:
    enabled: true
    exclude_paths:
    - config/engines.yml
  detekt:
    enabled: true
    exclude_paths:
    - config/engines.yml
  duplication:
    enabled: true
    exclude_paths:
    - config/engines.yml
  metrics:
    enabled: true
    exclude_paths:
    - config/engines.yml
  coverage:
    enabled: true
    exclude_paths:
    - config/engines.yml
exclude_paths:
- 'build/**'
- '**/src/test/**'
- '**/src/androidTest/**'
